### ISSUE TITLE
imagesLoaded is not defined

### ISSUE THREAD

**Issue by urgent** [RevContent/api-showcase#2]
On some wordpress templates I received this error:

`Uncaught ReferenceError: imagesLoaded is not defined request.onload @ revtoaster.min.js:1`

I fixed it by manually including imagesLoaded in <head>

https://desandro.github.io/imagesloaded/

**Comment by oste** [comment]
By process of elimination it sounds like you are using the Toaster widget. Make sure you are using the [minified](https://github.com/RevContent/api-showcase/blob/master/revcontent-api-showcase-toaster-1.0/build/revtoaster.min.js) or [packaged version](https://github.com/RevContent/api-showcase/blob/master/revcontent-api-showcase-toaster-1.0/build/revtoaster.pkgd.js)

If you are building the widget make sure you include the dependencies via Bower.
